### ISSUE TITLE
SSL/TLS connection fails in v0.27.0 (works in v0.26.0)

### ISSUE THREAD

**Issue by rz-ve** [yhirose/cpp-httplib#2301]
A TLS/HTTP request that returns HTTP 200 (HTML) using cpp-httplib v.0.26.0 returns HTTP 404 with JSON `{"errors":[{"code":9009,"message":"No Service Found"}]}` when built with v0.27.0. 

This is the exact code that I ran:

```cpp
httplib::SSLClient cli("roblox.com", 443);
cli.set_follow_location(true);

auto res = cli.Get("/");

if (!res)
    return 1;

std::cout << "status: " << res->status << "\n";
std::cout << "body: " << res->body.substr(0, 100) << "...\n";

return 0;
```

With v0.26.0:

```
status: 200
body:
<!DOCTYPE html>
<!--[if IE 8]><html class="ie8" ng-app="robloxApp"><![endif]-->
<!--[if gt IE 8]><!...
```

With v0.27.0:

```
status: 404
body: {"errors":[{"code":9009,"message":"No Service Found"}]}...
```

I used curl on the same machine and it returned status 200. I tried using different versions of OpenSSL from 3.0.18 up to 3.6.0 and it produced the same result. I compiled on Windows using Visual Studio.

I only had this issue with the site `https://roblox.com` (uses SNI) but this might have impacted other sites as well

**Comment by Quad-z** [comment]
so idk

**Comment by yhirose** [comment]
@rz-ve Could you please update httplib.h to v0.28.0? According to the following research, this problem should already be fixed in the newest version. Thanks!
https://github.com/yhirose/cpp-httplib/pull/2307

**Comment by rz-ve** [comment]
@yhirose Thanks for the reply. I have updated httplib.h to commit `f0990ca` (v0.28.0) the issue seems to still persist with the latest commit. I used the same code provided in the post but with different httplib.h version.

I have used both curl.h and winhttp.h and they worked completely fine as httplib v0.26.0 (commit `89c932f`)
This issue only impacts httplib versions v0.27.0 and above.

The problem was not fixed

**Comment by yhirose** [comment]
@rz-ve thanks for the report. I reopened it, and I'll take a look at it when I have time.
